### ISSUE TITLE
Request for report generation/ more complete data on the downloaded CSV for all projects

### ISSUE THREAD

**Issue by mtayco** [dapmsipd/pips#126]
Anticipating the possible data that we might need to generate the assessment/ summary report for the PIP, it might be better if we can include all possible data fields in the downloaded project list (pls see excel file with 2 tabs).

[data request to be generated from PIPS.xlsx](https://github.com/mlab817/pips/files/12925864/data.request.to.be.generated.from.PIPS.xlsx)

for the pivot table, can we generate that from the ipd_encoder2 account?  or will there be a dedicated PIPS account that will house all data needs (the project csv file and the data for the pivot table)? if this will be accessed via the "pip_reviewer" account, unfortunately Ali and I don't know the password..

**Comment by mlab817** [comment]
> Anticipating the possible data that we might need to generate the assessment/ summary report for the PIP, it might be better if we can include all possible data fields in the downloaded project list (pls see excel file with 2 tabs).

Please note that I did not include complex reports in the downloadable because they can *slow down* the system and affect all the users (try PIPOL for reference). For this one, I was thinking of emailing the excel file instead of directly downloading it to the user's computer.

> for the pivot table, can we generate that from the ipd_encoder2 account?

Any account with LEAD_REVIEWER role should be able to download ALL PAPs. Just make sure that all offices are assigned to it. Then, you can assign any user with that role.

Now, as for the pivot table, if you want a generated report, we have to define now what will be included in that report. That would include the following:

1. updating period (fy 2023)
2. submission status (submitted excluding returned) + action requested (for inclusion)
3. validation status (completed) + action recommended (include)
4. approval status (approved)

This is where it gets difficult. Ideally, only PAPs **approved** should be included in the **generated** report. However, given varying speed of IPD staff in updating pap statuses (and resolving issues), it's very difficult to generate a **reliable** report. So, my recommendation is to just export the raw data and have someone process them for report generation instead.

What the exported data will contain are:

1. Full project profile (except for non-profile fields like notes, contact info, etc.)
2. Investment per funding source (per PAP)
3. Investment per region (per PAP)
4. Investment per province (per PAP)

The one who will generate the final report should learn how to combine these sheets using Excel's power query.
