### ISSUE TITLE
History log does not show (Abaca Devt Project)

### ISSUE THREAD

**Issue by mtayco** [dapmsipd/pips#139]
Abaca Devt Project history shows only blank grey page:

![image](https://github.com/mlab817/pips/assets/143272008/9141d12f-9c3b-48fd-b565-b2cecf312dc1)

(other PAPs are fine)

**Comment by mlab817** [comment]
This error is being encountered when the action undertaken was **deleted** causing the data **newValues** to be an empty array instead of **null**.

**Comment by mtayco** [comment]
What "action undertaken" was deleted? How does this happen (to avoid in future)?

Also, does this mean po that the entire history cannot be recovered/retrieved?

**Comment by mlab817** [comment]
> What "action undertaken" was deleted? How does this happen (to avoid in future)?

Data for relationships are stored in their respective tables. For example, investment per funding source is stored in a table called fs_investments that looks like this:

| id | project_id | funding_source_id | y2022 | ... | y2029 |
|---|-----------|--------------------|--------|---|-------|
| 1  | 256           | 1 | | | |

When an entry is deleted in the frontend, say when the fs_investment is deleted, the data in the table, this particular line will be deleted _permanently_. The audit logs will then show an empty newValue to signify that the data has been deleted.

![Screenshot 2023-11-06 at 8 50 33 AM](https://github.com/mlab817/pips/assets/29625844/3005716d-5927-4c1d-a7a5-0e85302f0bdd)

Now, the reason we _don't_ prevent permanent deletion of this entry is because when the user adds another entry given this specific project_id x funding_source_id combination, if the previous entry has not been deleted permanently, the database will throw an error saying that a similar combination already exists because of unique index to prevent duplication at the database level.

> Also, does this mean po that the entire history cannot be recovered/retrieved?

Yes, you can't restore it, but you can still view it in audit logs are stored in another table so it's still possible to view them like in this case, you can still see the previous values in the audit logs.

**HOWEVER, they will eventually be lost because we also need to clean up the audit logs as they take up too much space and may cause our database to slow down.**
