### ISSUE TITLE
Inclusion of ODA option in the DA PIPS Reviewer Accounts filter 

### ISSUE THREAD

**Issue by AlexEstoesta** [dapmsipd/pips#42]
Per Ms Verly of PDS, she noticed that there is no ODA option for the filter in the system, whereas this was mentioned during the hands on session for IP reviewers. Suggestion to include this option to assist the PDS IP reviewers.

**Comment by mlab817** [comment]
**Not feasible because it will result in exclusion of NG-funded PAPs**

The filters being requested by the PDS is not feasible. An immediate example is: all CIPs will go through clearinghouse, which includes NG funded PAPs with investment cost of 2.5 billion and up. Implementing ODA-filtering will exclude these PAPs.

It is tempting to say that we can add a filter of 2.5 billion and above for NG-funded PAPs. However, since the purpose of the filter is to **limit** what users see, this filter will apply to ALL PAPs, meaning, they will only see PAPs with cost over 2.5 B. This will exclude grant PAP, which are not CIP (less than 150M).

PDS can also provide a list of their PAPs so IPD can analyze and formulate an appropriate filter for them that may solve the problems cited above. However, I doubt any solution would work without _hardcoding_ it in the PIPS codebase (Hardcoding is not transparent and can only be understood by the developer making it difficult to troubleshoot and maintain).

**Assistance is needed by IPD for identifying _legitimate_ projects**

IPD should also consider that PDS can help them identify PAPs that would require clearinghouse processing. This means these PAPs will be considered proposals under Tier 2 instead and IPD can identify the proper channels to review these projects. 

**PDS is not required to act on projects that will not go through clearinghouse**

PDS can always just ignore PAPs that are not within their purview although it would also be helpful, but to reiterate, optional, if they can provide comment that the PAP will not require their processing.

**Alternative solution**

An alternative solution I could think of is to expand this filtering to include the following:

1. CIP
2. CIP types
3. ICC resubmission
4. Main funding source
5. Total cost (minimum)

This way, they can do their own filtering as needed.

<img width="1680" alt="Screenshot 2023-09-08 at 7 21 02 PM" src="https://github.com/mlab817/pips/assets/29625844/a752bbd4-1da4-4383-9e33-4059342b3e24">
