### ISSUE TITLE
Validation status for returned PAPs to show more generic status

### ISSUE THREAD

**Issue by mtayco** [dapmsipd/pips#79]
Although most PAPs being returned to encoders are for their finalization/ submission of additional inputs, it does seem appropriate to have them labeled as "Awaiting_resubmission"; 
![image](https://github.com/mlab817/pips/assets/143272008/81797287-598f-423a-8f78-76496913c611)

however there are PAPs being returned also which are NOT for resubmission but for DELETION, for reasons such as:
- the PAP will be subsumed to another program
- the PAP will be incorporated in the Project profile encoded by another DA Implementing Office acting as the PMO/ sole encoder for the project
- the encoder created a entry and submitted the PAP, but the program/ project itself is already preloaded from last year's formulation

.. thus, suggestion if rather than "Awaiting_resubmission", to  restate it into something like "Awaiting_further action" to avoid confusion

**Comment by mlab817** [comment]
@mtayco 

actually, said PAPs should be marked as "EXCLUDE(D)" since they will not be included in the submission to NEDA PIPOL. Validation remarks should contain info on why the PAP was to be excluded, e.g. the reasons you mentioned. Only PAPs that would actually be submitted to NEDA should undergo further validation.

in addition, this is something that should be run by higher ups of TechSec since it should not decide on which PAP will be included/excluded. the keyword here is "action recommended".

**Comment by mtayco** [comment]
noted on this sir les. thanks.
